name: Deploy Portfolio (Production)

on:
  push:
    tags:
      - 'portfolio@*'

permissions:
  contents: read

concurrency:
  group: deploy-portfolio-production
  cancel-in-progress: false

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_PORTFOLIO }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install Vercel CLI
        run: npm install --global vercel@34.0.0

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token="$VERCEL_TOKEN"

      - name: Build Project Artifacts
        run: vercel build --prod --token="$VERCEL_TOKEN"

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token="$VERCEL_TOKEN"
